# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  loginapi:
    image: loginapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5067:5067
